### ISSUE TITLE
model.py

### ISSUE THREAD

**Issue by wcyy0123** [Anirudh257/strm#14]
Hi,
Thanks for sharing the code. I try to run the model.py to look through the architecture of the model and test if the model can work.
Error occurs:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)
```

**Comment by Anirudh257** [comment]
Hi, you can try running parallelly on multiple GPUs or shift the tensor to **.cuda** as n ad-hoc technique.

**Comment by wcyy0123** [comment]
The code I run was:
```
if __name__ == "__main__":
    class ArgsObject(object):
        def __init__(self):
            self.trans_linear_in_dim = 512
            self.trans_linear_out_dim = 128

            self.way = 5
            self.shot = 1
            self.query_per_class = 5
            self.trans_dropout = 0.1
            self.seq_len = 8 
            self.img_size = 84
            self.method = "resnet18"
            self.num_gpus = 1
            self.temp_set = [2,3]
    args = ArgsObject()
    #torch.manual_seed(STRM(args))
        
    support_imgs = torch.rand(args.way * args.shot * args.seq_len,3, args.img_size, args.img_size).cuda()
    target_imgs = torch.rand(args.way * args.query_per_class * args.seq_len ,3, args.img_size, args.img_size).cuda()
    support_labels = torch.tensor([0,1,2,3,4])
    support_labels.cuda()

    model = CNN_STRM(args)
    #model.to(device)
    model.cuda()
    
    out = model(support_imgs, support_labels, target_imgs)
    #out = CNN_STRM(support_imgs, support_labels, target_imgs)

    print("STRM returns the distances from each query to each class prototype.  Use these as logits.  Shape: {}".format(out['logits'].shape))
```
The error is:
```
Traceback (most recent call last):
  File "strm.py", line 565, in <module>
    out = model(support_imgs, support_labels, target_imgs)
  File "D:\software\program\Anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "strm.py", line 493, in forward
    all_logits_post_pat = [n(context_features, context_labels, target_features)['logits'] for n in self.new_dist_loss_post_pat]
  File "strm.py", line 493, in <listcomp>
    all_logits_post_pat = [n(context_features, context_labels, target_features)['logits'] for n in self.new_dist_loss_post_pat]
  File "D:\software\program\Anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "strm.py", line 87, in forward
    query_embed = self.clsW(queries.view(-1, self.args.trans_linear_in_dim*self.temporal_set_size)) # 560[20x28] x 1024
  File "D:\software\program\Anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\software\program\Anaconda3\envs\pytorch1\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)
```

**Comment by wcyy0123** [comment]
I have solved it by changing
` self.clsW = nn.Linear(self.args.trans_linear_in_dim * self.temporal_set_size, self.args.trans_linear_in_dim//2)`
to
` self.clsW = nn.Linear(self.args.trans_linear_in_dim * self.temporal_set_size, self.args.trans_linear_in_dim//2,device=device)`

**Comment by wcyy0123** [comment]
I have solved it by changing
```
self.clsW = nn.Linear(self.args.trans_linear_in_dim * self.temporal_set_size, self.args.trans_linear_in_dim//2)
```
to
```
self.clsW = nn.Linear(self.args.trans_linear_in_dim * self.temporal_set_size, self.args.trans_linear_in_dim//2,device=device)
```
Thank you very much!

**Comment by Anirudh257** [comment]
Welcome. Thanks for commenting your solution as well!
